version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - ifElseChain
      - octalLiteral
      - wrapperFunc

  gocyclo:
    min-complexity: 15

  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - misspell

issues:
  exclude-dirs:
    - testdata
    - vendor
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo

    # Ignore shadowing of err
    - linters: [govet]
      text: 'declaration of "(err|ctx)" shadows declaration at'

    # Interface design constraints - cannot change without breaking API
    - linters: [gocritic]
      text: "hugeParam"
    - linters: [gocritic]
      text: "unnamedResult"

    # Intentional cleanup error ignores - already using _ prefix
    - linters: [errcheck]
      text: "Error return value of.*is not checked"
      source: "_ = .*\\.Close\\(\\)"
    - linters: [errcheck]
      text: "Error return value of.*is not checked"
      source: "_ = os\\.Remove"
    - linters: [errcheck]
      text: "Error return value of.*is not checked"
      source: "_ = .*Close\\(\\)"

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3