# Minimal golangci-lint configuration compatible with v8+

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - revive

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo

    # Ignore missing comments on exported types/functions in examples
    - path: examples/
      linters:
        - revive

    # Expected subprocess execution - core SDK functionality
    - linters:
        - gosec
      text: "G204"

    # Intentional cleanup error ignores
    - linters:
        - errcheck
      source: "_ = .*\\.Close\\(\\)"

    - linters:
        - errcheck
      source: "_ = os\\.Remove"

  max-issues-per-linter: 50