version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
