version: 2

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/severity1/claude-code-sdk-go

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - ifElseChain
      - octalLiteral
      - wrapperFunc

  gocyclo:
    min-complexity: 15

  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

  lll:
    line-length: 120

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo

    - path: examples/
      linters:
        - revive
      text: "exported.*should have comment.*or be unexported"

    - linters:
        - govet
      text: 'declaration of "(err|ctx)" shadows declaration at'

    - linters:
        - errcheck
      source: "_ = .*\\.Close\\(\\)"

    - linters:
        - errcheck
      source: "_ = os\\.Remove"

  max-issues-per-linter: 50
  max-same-issues: 3